POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "sneha_sharma",
  "name": "Sneha Sharma",
  "password": "sneha@159",
  "gender": "female",
  "location": "Delhi"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sneha_sharma",
  "password": "sneha@159"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "sneha_sharma",
  "oldPassword": "sneha@159",
  "newPassword": "sneha@143"
}