POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "praneeth_teja",
  "name": "Praneeth Teja",
  "password": "neethu@156",
  "gender": "male",
  "location": "Delhi"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "praneeth_teja",
  "password": "neethu@156"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "praneeth_teja",
  "oldPassword": "neethu@156",
  "newPassword": "neethu@153"
}
